language: go

go:
  - 1.11.4

env:
  - GO111MODULE=on

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379 --daemonize yes
  - sudo redis-server /etc/redis/redis.conf --port 6479 --daemonize yes
script: go test diff-redis/src -v